//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CfdiService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since message GeneraConstanciaRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="www.XMLWebServiceSoapHeaderAuth.net/GeneraConstancia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CfdiService.ServiceReference1.GeneraConstanciaResponse GeneraConstancia(CfdiService.ServiceReference1.GeneraConstanciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.XMLWebServiceSoapHeaderAuth.net/GeneraConstancia", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiService.ServiceReference1.GeneraConstanciaResponse> GeneraConstanciaAsync(CfdiService.ServiceReference1.GeneraConstanciaRequest request);
        
        // CODEGEN: Generating message contract since message GeneraRefrendoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="www.XMLWebServiceSoapHeaderAuth.net/GeneraRefrendo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CfdiService.ServiceReference1.GeneraRefrendoResponse GeneraRefrendo(CfdiService.ServiceReference1.GeneraRefrendoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.XMLWebServiceSoapHeaderAuth.net/GeneraRefrendo", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiService.ServiceReference1.GeneraRefrendoResponse> GeneraRefrendoAsync(CfdiService.ServiceReference1.GeneraRefrendoRequest request);
        
        // CODEGEN: Generating message contract since message ValidaConstanciaRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="www.XMLWebServiceSoapHeaderAuth.net/ValidaConstancia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CfdiService.ServiceReference1.ValidaConstanciaResponse ValidaConstancia(CfdiService.ServiceReference1.ValidaConstanciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.XMLWebServiceSoapHeaderAuth.net/ValidaConstancia", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiService.ServiceReference1.ValidaConstanciaResponse> ValidaConstanciaAsync(CfdiService.ServiceReference1.ValidaConstanciaRequest request);
        
        // CODEGEN: Generating message contract since message ConsultaCertificadoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="www.XMLWebServiceSoapHeaderAuth.net/ConsultaCertificado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CfdiService.ServiceReference1.ConsultaCertificadoResponse ConsultaCertificado(CfdiService.ServiceReference1.ConsultaCertificadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.XMLWebServiceSoapHeaderAuth.net/ConsultaCertificado", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiService.ServiceReference1.ConsultaCertificadoResponse> ConsultaCertificadoAsync(CfdiService.ServiceReference1.ConsultaCertificadoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net")]
    public partial class AuthSoapHd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string claveField;
        
        private string entidadField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
                this.RaisePropertyChanged("Entidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net")]
    public partial class TConsultaCertificado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoField;
        
        private string descripcionField;
        
        private long folioField;
        
        private string certificadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
                this.RaisePropertyChanged("Folio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Certificado {
            get {
                return this.certificadoField;
            }
            set {
                this.certificadoField = value;
                this.RaisePropertyChanged("Certificado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net")]
    public partial class TValidaConstancia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoField;
        
        private string descripcionField;
        
        private long folioField;
        
        private string digestionField;
        
        private string fechaField;
        
        private string serieField;
        
        private string certificadoPscField;
        
        private string fechaInicialField;
        
        private string serieInicialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
                this.RaisePropertyChanged("Folio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Digestion {
            get {
                return this.digestionField;
            }
            set {
                this.digestionField = value;
                this.RaisePropertyChanged("Digestion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("Serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CertificadoPsc {
            get {
                return this.certificadoPscField;
            }
            set {
                this.certificadoPscField = value;
                this.RaisePropertyChanged("CertificadoPsc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FechaInicial {
            get {
                return this.fechaInicialField;
            }
            set {
                this.fechaInicialField = value;
                this.RaisePropertyChanged("FechaInicial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SerieInicial {
            get {
                return this.serieInicialField;
            }
            set {
                this.serieInicialField = value;
                this.RaisePropertyChanged("SerieInicial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net")]
    public partial class TConstancia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoField;
        
        private string descripcionField;
        
        private string constanciaField;
        
        private long folioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Constancia {
            get {
                return this.constanciaField;
            }
            set {
                this.constanciaField = value;
                this.RaisePropertyChanged("Constancia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long Folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
                this.RaisePropertyChanged("Folio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeneraConstancia", WrapperNamespace="www.XMLWebServiceSoapHeaderAuth.net", IsWrapped=true)]
    public partial class GeneraConstanciaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net")]
        public CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", Order=0)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", Order=1)]
        public string solicitud;
        
        public GeneraConstanciaRequest() {
        }
        
        public GeneraConstanciaRequest(CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd, string referencia, string solicitud) {
            this.AuthSoapHd = AuthSoapHd;
            this.referencia = referencia;
            this.solicitud = solicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeneraConstanciaResponse", WrapperNamespace="www.XMLWebServiceSoapHeaderAuth.net", IsWrapped=true)]
    public partial class GeneraConstanciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", Order=0)]
        public CfdiService.ServiceReference1.TConstancia GeneraConstanciaResult;
        
        public GeneraConstanciaResponse() {
        }
        
        public GeneraConstanciaResponse(CfdiService.ServiceReference1.TConstancia GeneraConstanciaResult) {
            this.GeneraConstanciaResult = GeneraConstanciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeneraRefrendo", WrapperNamespace="www.XMLWebServiceSoapHeaderAuth.net", IsWrapped=true)]
    public partial class GeneraRefrendoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net")]
        public CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", Order=0)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", Order=1)]
        public string solicitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", Order=2)]
        public string refrendo;
        
        public GeneraRefrendoRequest() {
        }
        
        public GeneraRefrendoRequest(CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd, string referencia, string solicitud, string refrendo) {
            this.AuthSoapHd = AuthSoapHd;
            this.referencia = referencia;
            this.solicitud = solicitud;
            this.refrendo = refrendo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeneraRefrendoResponse", WrapperNamespace="www.XMLWebServiceSoapHeaderAuth.net", IsWrapped=true)]
    public partial class GeneraRefrendoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", Order=0)]
        public CfdiService.ServiceReference1.TConstancia GeneraRefrendoResult;
        
        public GeneraRefrendoResponse() {
        }
        
        public GeneraRefrendoResponse(CfdiService.ServiceReference1.TConstancia GeneraRefrendoResult) {
            this.GeneraRefrendoResult = GeneraRefrendoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidaConstancia", WrapperNamespace="www.XMLWebServiceSoapHeaderAuth.net", IsWrapped=true)]
    public partial class ValidaConstanciaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net")]
        public CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", Order=0)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", Order=1)]
        public string constancia;
        
        public ValidaConstanciaRequest() {
        }
        
        public ValidaConstanciaRequest(CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd, string referencia, string constancia) {
            this.AuthSoapHd = AuthSoapHd;
            this.referencia = referencia;
            this.constancia = constancia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidaConstanciaResponse", WrapperNamespace="www.XMLWebServiceSoapHeaderAuth.net", IsWrapped=true)]
    public partial class ValidaConstanciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", Order=0)]
        public CfdiService.ServiceReference1.TValidaConstancia ValidaConstanciaResult;
        
        public ValidaConstanciaResponse() {
        }
        
        public ValidaConstanciaResponse(CfdiService.ServiceReference1.TValidaConstancia ValidaConstanciaResult) {
            this.ValidaConstanciaResult = ValidaConstanciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCertificado", WrapperNamespace="www.XMLWebServiceSoapHeaderAuth.net", IsWrapped=true)]
    public partial class ConsultaCertificadoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net")]
        public CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", Order=0)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", Order=1)]
        public string certificadoPsc;
        
        public ConsultaCertificadoRequest() {
        }
        
        public ConsultaCertificadoRequest(CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd, string referencia, string certificadoPsc) {
            this.AuthSoapHd = AuthSoapHd;
            this.referencia = referencia;
            this.certificadoPsc = certificadoPsc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaCertificadoResponse", WrapperNamespace="www.XMLWebServiceSoapHeaderAuth.net", IsWrapped=true)]
    public partial class ConsultaCertificadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.XMLWebServiceSoapHeaderAuth.net", Order=0)]
        public CfdiService.ServiceReference1.TConsultaCertificado ConsultaCertificadoResult;
        
        public ConsultaCertificadoResponse() {
        }
        
        public ConsultaCertificadoResponse(CfdiService.ServiceReference1.TConsultaCertificado ConsultaCertificadoResult) {
            this.ConsultaCertificadoResult = ConsultaCertificadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : CfdiService.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<CfdiService.ServiceReference1.WebServiceSoap>, CfdiService.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiService.ServiceReference1.GeneraConstanciaResponse CfdiService.ServiceReference1.WebServiceSoap.GeneraConstancia(CfdiService.ServiceReference1.GeneraConstanciaRequest request) {
            return base.Channel.GeneraConstancia(request);
        }
        
        public CfdiService.ServiceReference1.TConstancia GeneraConstancia(CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd, string referencia, string solicitud) {
            CfdiService.ServiceReference1.GeneraConstanciaRequest inValue = new CfdiService.ServiceReference1.GeneraConstanciaRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            inValue.referencia = referencia;
            inValue.solicitud = solicitud;
            CfdiService.ServiceReference1.GeneraConstanciaResponse retVal = ((CfdiService.ServiceReference1.WebServiceSoap)(this)).GeneraConstancia(inValue);
            return retVal.GeneraConstanciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiService.ServiceReference1.GeneraConstanciaResponse> CfdiService.ServiceReference1.WebServiceSoap.GeneraConstanciaAsync(CfdiService.ServiceReference1.GeneraConstanciaRequest request) {
            return base.Channel.GeneraConstanciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiService.ServiceReference1.GeneraConstanciaResponse> GeneraConstanciaAsync(CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd, string referencia, string solicitud) {
            CfdiService.ServiceReference1.GeneraConstanciaRequest inValue = new CfdiService.ServiceReference1.GeneraConstanciaRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            inValue.referencia = referencia;
            inValue.solicitud = solicitud;
            return ((CfdiService.ServiceReference1.WebServiceSoap)(this)).GeneraConstanciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiService.ServiceReference1.GeneraRefrendoResponse CfdiService.ServiceReference1.WebServiceSoap.GeneraRefrendo(CfdiService.ServiceReference1.GeneraRefrendoRequest request) {
            return base.Channel.GeneraRefrendo(request);
        }
        
        public CfdiService.ServiceReference1.TConstancia GeneraRefrendo(CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd, string referencia, string solicitud, string refrendo) {
            CfdiService.ServiceReference1.GeneraRefrendoRequest inValue = new CfdiService.ServiceReference1.GeneraRefrendoRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            inValue.referencia = referencia;
            inValue.solicitud = solicitud;
            inValue.refrendo = refrendo;
            CfdiService.ServiceReference1.GeneraRefrendoResponse retVal = ((CfdiService.ServiceReference1.WebServiceSoap)(this)).GeneraRefrendo(inValue);
            return retVal.GeneraRefrendoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiService.ServiceReference1.GeneraRefrendoResponse> CfdiService.ServiceReference1.WebServiceSoap.GeneraRefrendoAsync(CfdiService.ServiceReference1.GeneraRefrendoRequest request) {
            return base.Channel.GeneraRefrendoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiService.ServiceReference1.GeneraRefrendoResponse> GeneraRefrendoAsync(CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd, string referencia, string solicitud, string refrendo) {
            CfdiService.ServiceReference1.GeneraRefrendoRequest inValue = new CfdiService.ServiceReference1.GeneraRefrendoRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            inValue.referencia = referencia;
            inValue.solicitud = solicitud;
            inValue.refrendo = refrendo;
            return ((CfdiService.ServiceReference1.WebServiceSoap)(this)).GeneraRefrendoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiService.ServiceReference1.ValidaConstanciaResponse CfdiService.ServiceReference1.WebServiceSoap.ValidaConstancia(CfdiService.ServiceReference1.ValidaConstanciaRequest request) {
            return base.Channel.ValidaConstancia(request);
        }
        
        public CfdiService.ServiceReference1.TValidaConstancia ValidaConstancia(CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd, string referencia, string constancia) {
            CfdiService.ServiceReference1.ValidaConstanciaRequest inValue = new CfdiService.ServiceReference1.ValidaConstanciaRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            inValue.referencia = referencia;
            inValue.constancia = constancia;
            CfdiService.ServiceReference1.ValidaConstanciaResponse retVal = ((CfdiService.ServiceReference1.WebServiceSoap)(this)).ValidaConstancia(inValue);
            return retVal.ValidaConstanciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiService.ServiceReference1.ValidaConstanciaResponse> CfdiService.ServiceReference1.WebServiceSoap.ValidaConstanciaAsync(CfdiService.ServiceReference1.ValidaConstanciaRequest request) {
            return base.Channel.ValidaConstanciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiService.ServiceReference1.ValidaConstanciaResponse> ValidaConstanciaAsync(CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd, string referencia, string constancia) {
            CfdiService.ServiceReference1.ValidaConstanciaRequest inValue = new CfdiService.ServiceReference1.ValidaConstanciaRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            inValue.referencia = referencia;
            inValue.constancia = constancia;
            return ((CfdiService.ServiceReference1.WebServiceSoap)(this)).ValidaConstanciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiService.ServiceReference1.ConsultaCertificadoResponse CfdiService.ServiceReference1.WebServiceSoap.ConsultaCertificado(CfdiService.ServiceReference1.ConsultaCertificadoRequest request) {
            return base.Channel.ConsultaCertificado(request);
        }
        
        public CfdiService.ServiceReference1.TConsultaCertificado ConsultaCertificado(CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd, string referencia, string certificadoPsc) {
            CfdiService.ServiceReference1.ConsultaCertificadoRequest inValue = new CfdiService.ServiceReference1.ConsultaCertificadoRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            inValue.referencia = referencia;
            inValue.certificadoPsc = certificadoPsc;
            CfdiService.ServiceReference1.ConsultaCertificadoResponse retVal = ((CfdiService.ServiceReference1.WebServiceSoap)(this)).ConsultaCertificado(inValue);
            return retVal.ConsultaCertificadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiService.ServiceReference1.ConsultaCertificadoResponse> CfdiService.ServiceReference1.WebServiceSoap.ConsultaCertificadoAsync(CfdiService.ServiceReference1.ConsultaCertificadoRequest request) {
            return base.Channel.ConsultaCertificadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiService.ServiceReference1.ConsultaCertificadoResponse> ConsultaCertificadoAsync(CfdiService.ServiceReference1.AuthSoapHd AuthSoapHd, string referencia, string certificadoPsc) {
            CfdiService.ServiceReference1.ConsultaCertificadoRequest inValue = new CfdiService.ServiceReference1.ConsultaCertificadoRequest();
            inValue.AuthSoapHd = AuthSoapHd;
            inValue.referencia = referencia;
            inValue.certificadoPsc = certificadoPsc;
            return ((CfdiService.ServiceReference1.WebServiceSoap)(this)).ConsultaCertificadoAsync(inValue);
        }
    }
}
