//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CfdiService.ReachcoreService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReachcoreService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneraConstancia", ReplyAction="*")]
        CfdiService.ReachcoreService.GeneraConstanciaResponse GeneraConstancia(CfdiService.ReachcoreService.GeneraConstanciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneraConstancia", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiService.ReachcoreService.GeneraConstanciaResponse> GeneraConstanciaAsync(CfdiService.ReachcoreService.GeneraConstanciaRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneraEstampilla", ReplyAction="*")]
        CfdiService.ReachcoreService.GeneraEstampillaResponse GeneraEstampilla(CfdiService.ReachcoreService.GeneraEstampillaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneraEstampilla", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiService.ReachcoreService.GeneraEstampillaResponse> GeneraEstampillaAsync(CfdiService.ReachcoreService.GeneraEstampillaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GeneraConstanciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GeneraConstancia", Namespace="http://tempuri.org/", Order=0)]
        public CfdiService.ReachcoreService.GeneraConstanciaRequestBody Body;
        
        public GeneraConstanciaRequest() {
        }
        
        public GeneraConstanciaRequest(CfdiService.ReachcoreService.GeneraConstanciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GeneraConstanciaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string expediente;
        
        public GeneraConstanciaRequestBody() {
        }
        
        public GeneraConstanciaRequestBody(string usuario, string clave, string expediente) {
            this.usuario = usuario;
            this.clave = clave;
            this.expediente = expediente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GeneraConstanciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GeneraConstanciaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CfdiService.ReachcoreService.GeneraConstanciaResponseBody Body;
        
        public GeneraConstanciaResponse() {
        }
        
        public GeneraConstanciaResponse(CfdiService.ReachcoreService.GeneraConstanciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GeneraConstanciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GeneraConstanciaResult;
        
        public GeneraConstanciaResponseBody() {
        }
        
        public GeneraConstanciaResponseBody(string GeneraConstanciaResult) {
            this.GeneraConstanciaResult = GeneraConstanciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GeneraEstampillaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GeneraEstampilla", Namespace="http://tempuri.org/", Order=0)]
        public CfdiService.ReachcoreService.GeneraEstampillaRequestBody Body;
        
        public GeneraEstampillaRequest() {
        }
        
        public GeneraEstampillaRequest(CfdiService.ReachcoreService.GeneraEstampillaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GeneraEstampillaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string digestion;
        
        public GeneraEstampillaRequestBody() {
        }
        
        public GeneraEstampillaRequestBody(string usuario, string clave, string digestion) {
            this.usuario = usuario;
            this.clave = clave;
            this.digestion = digestion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GeneraEstampillaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GeneraEstampillaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CfdiService.ReachcoreService.GeneraEstampillaResponseBody Body;
        
        public GeneraEstampillaResponse() {
        }
        
        public GeneraEstampillaResponse(CfdiService.ReachcoreService.GeneraEstampillaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GeneraEstampillaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GeneraEstampillaResult;
        
        public GeneraEstampillaResponseBody() {
        }
        
        public GeneraEstampillaResponseBody(string GeneraEstampillaResult) {
            this.GeneraEstampillaResult = GeneraEstampillaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : CfdiService.ReachcoreService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<CfdiService.ReachcoreService.ServiceSoap>, CfdiService.ReachcoreService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiService.ReachcoreService.GeneraConstanciaResponse CfdiService.ReachcoreService.ServiceSoap.GeneraConstancia(CfdiService.ReachcoreService.GeneraConstanciaRequest request) {
            return base.Channel.GeneraConstancia(request);
        }
        
        public string GeneraConstancia(string usuario, string clave, string expediente) {
            CfdiService.ReachcoreService.GeneraConstanciaRequest inValue = new CfdiService.ReachcoreService.GeneraConstanciaRequest();
            inValue.Body = new CfdiService.ReachcoreService.GeneraConstanciaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.expediente = expediente;
            CfdiService.ReachcoreService.GeneraConstanciaResponse retVal = ((CfdiService.ReachcoreService.ServiceSoap)(this)).GeneraConstancia(inValue);
            return retVal.Body.GeneraConstanciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiService.ReachcoreService.GeneraConstanciaResponse> CfdiService.ReachcoreService.ServiceSoap.GeneraConstanciaAsync(CfdiService.ReachcoreService.GeneraConstanciaRequest request) {
            return base.Channel.GeneraConstanciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiService.ReachcoreService.GeneraConstanciaResponse> GeneraConstanciaAsync(string usuario, string clave, string expediente) {
            CfdiService.ReachcoreService.GeneraConstanciaRequest inValue = new CfdiService.ReachcoreService.GeneraConstanciaRequest();
            inValue.Body = new CfdiService.ReachcoreService.GeneraConstanciaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.expediente = expediente;
            return ((CfdiService.ReachcoreService.ServiceSoap)(this)).GeneraConstanciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiService.ReachcoreService.GeneraEstampillaResponse CfdiService.ReachcoreService.ServiceSoap.GeneraEstampilla(CfdiService.ReachcoreService.GeneraEstampillaRequest request) {
            return base.Channel.GeneraEstampilla(request);
        }
        
        public string GeneraEstampilla(string usuario, string clave, string digestion) {
            CfdiService.ReachcoreService.GeneraEstampillaRequest inValue = new CfdiService.ReachcoreService.GeneraEstampillaRequest();
            inValue.Body = new CfdiService.ReachcoreService.GeneraEstampillaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.digestion = digestion;
            CfdiService.ReachcoreService.GeneraEstampillaResponse retVal = ((CfdiService.ReachcoreService.ServiceSoap)(this)).GeneraEstampilla(inValue);
            return retVal.Body.GeneraEstampillaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiService.ReachcoreService.GeneraEstampillaResponse> CfdiService.ReachcoreService.ServiceSoap.GeneraEstampillaAsync(CfdiService.ReachcoreService.GeneraEstampillaRequest request) {
            return base.Channel.GeneraEstampillaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiService.ReachcoreService.GeneraEstampillaResponse> GeneraEstampillaAsync(string usuario, string clave, string digestion) {
            CfdiService.ReachcoreService.GeneraEstampillaRequest inValue = new CfdiService.ReachcoreService.GeneraEstampillaRequest();
            inValue.Body = new CfdiService.ReachcoreService.GeneraEstampillaRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            inValue.Body.digestion = digestion;
            return ((CfdiService.ReachcoreService.ServiceSoap)(this)).GeneraEstampillaAsync(inValue);
        }
    }
}
